### ISSUE TITLE
Link to README on UD page is broken

### ISSUE THREAD

**Issue by ceramisch** [UniversalDependencies/UD_Portuguese-BR#2]
The link on the main UD page, on the table, is broken for the treebank Portuguese-BR.
It currently points to:
https://github.com/UniversalDependencies/UD_Portuguese-BR/blob/dev/README.txt

But it should point to:
https://github.com/UniversalDependencies/UD_Portuguese-BR/blob/dev/README.md

**Comment by arademaker** [comment]
Fixed in https://github.com/UniversalDependencies/docs/commit/d4488ebe1764f5a1b3b825dcf225385486bb9e6b

**Comment by dan-zeman** [comment]
Sorry, @arademaker, this did not fix the problem. Please do not edit `_includes/at_glance.html`. This file is generated by a script (although the script is not invoked automatically yet). We (me and @fginter) have to make sure that the script sees the most recent contents of UD_Portuguese-BR.

**Comment by dan-zeman** [comment]
Fixed in https://github.com/UniversalDependencies/docs/commit/7b0c1b78678d619a887e9cd9ca0d8dd4dff0a068
